app:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid &&  && bundle exec puma -C config/puma.rb
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
postgres:
  image: postgres:9.6
  ports:
    - "5432"
redis:
  image: redis:3.2
  ports:
    - '6379:6379'
sidekiq:
  build: .
  command: bash -c "bundle exec sidekiq -C config/sidekiq.yml"
  links:
    - redis
  volumes:
    - .:/app
