# File storage
# AWS (fog-aws)
# AWS_KEY: 
# AWS_REGION: "us-east-1"
# AWS_SECRET: 

# Mandrill
SMTP_ADDRESS: "smtp.mandrillapp.com"
SMTP_DOMAIN: "localhost"
SMTP_PASSWORD: 
SMTP_USERNAME: 

test:
  CLIENT_ORIGIN: "http://localhost:4200"
  EMAIL_ORIGIN: "http://localhost:4200"
  REDIS_URL: "redis://redis:6379"
  # STRIPE_PUBLISHABLE_KEY:
  # STRIPE_SECRET_KEY:

development:
  # AWS_BUCKET: 
  CLIENT_ORIGIN: "http://localhost:4200"
  EMAIL_ORIGIN: "http://localhost:4200"
  # Enable logging in development
  RAILS_LOG_TO_STDOUT: "enabled"
  REDIS_URL: "redis://redis:6379"
  # STRIPE_PUBLISHABLE_KEY:
  # STRIPE_SECRET_KEY:

# staging:
#   AWS_BUCKET: 
#   CLIENT_ORIGIN:
#   EMAIL_ORIGIN:
#   STRIPE_PUBLISHABLE_KEY:
#   STRIPE_SECRET_KEY:

# production:
#   AWS_BUCKET:
#   CLIENT_ORIGIN:
#   EMAIL_ORIGIN: 
#   STRIPE_PUBLISHABLE_KEY:
#   STRIPE_SECRET_KEY:


